#!/usr/bin/env python

from anod.build import UxasBuilder
from anod.util import (check_common_tools, create_anod_context,
                       create_anod_sandbox)

from e3.anod.context import AnodContext
from e3.anod.sandbox import SandBox
from e3.env import BaseEnv
from e3.main import Main

import logging
import os
import sys

ROOT_DIR = os.path.dirname(os.path.abspath(__file__))
SPEC_DIR = os.path.join(ROOT_DIR, 'specs')
SBX_DIR = os.path.join(ROOT_DIR, 'sbx')

# Uxas repo root directory
OPENUXAS_ROOT_DIR = os.path.dirname(ROOT_DIR)
os.environ['OPENUXAS_ROOT_DIR'] = OPENUXAS_ROOT_DIR


if __name__ == '__main__':
    m = Main()
    m.argument_parser.add_argument(
        'spec_name', help='spec to build. This is '
        'the basename of an .anod file (without the extension)')
    m.argument_parser.add_argument('--qualifier', help='optional qualifier')
    m.argument_parser.add_argument(
        '--sandbox-dir',
        help='directory in which build artefacts are stored',
        default=SBX_DIR)
    m.argument_parser.add_argument(
        '--force',
        help='force rebuild of everything',
        action="store_true",
        default=False)
    m.parse_args()

    check_common_tools()

    ac = create_anod_context(SPEC_DIR)
    sbx = create_anod_sandbox(m.args.sandbox_dir, SPEC_DIR)

    sbx.create_dirs()

    ac.add_anod_action(name=m.args.spec_name,
                       primitive='build',
                       qualifier=m.args.qualifier,
                       sandbox=sbx,
                       upload=False,
                       env=BaseEnv.from_env())
    actions = ac.schedule(resolver=ac.always_create_source_resolver)

    walker = UxasBuilder(actions, sandbox=sbx, force=m.args.force)

    # TODO: something with walker.job_status['root'], assuming we can get a
    # useful value there. Right now, it's always 'unknown'
