#!/usr/bin/env python

"""
Simple front-end to the task-specific anod scripts contained in lib.
"""

from e3.main import Main

from argparse import SUPPRESS

import logging
import os
import sys


if __name__ == '__main__':
    m = Main()
    command_arg = m.argument_parser.add_argument(
        'command',
        choices=['build', 'setenv', 'devel-setup'],
        help='the subcommand to be run.',
    )

    m.parse_args(known_args_only=True)

    # Now that we've parsed the command, we don't want it showing up in help
    # for the subcommands
    command_arg.help = SUPPRESS

    if m.args.command == 'build':
        from lib.anod_build import do_build

        exit(do_build(m))

    elif m.args.command == 'setenv':
        from lib.anod_setenv import do_setenv

        exit(do_setenv(m))

    elif m.args.command == 'devel-setup':
        from lib.anod_devel_setup import do_devel_setup

        exit(do_devel_setup(m))

    else:
        # cannot happen
        exit(4)
