#! /bin/sh

# First, let's set up our environment.
eval `./anod-setenv uxas`
eval `./anod-setenv uxas-ada`
eval `./anod-setenv amase`

# Now, as a sanity check, let's make sure that uxas and amase have been built.
if [ ! -f ${UXAS_INSTALL_DIR}/bin/uxas ]; then
    echo "You need to build OpenUxAS first, using \`./anod-build uxas\`"
    return 1
fi

if [ ! -f ${AMASE_SOURCE_DIR}/OpenAMASE/build/classes/MakeDistribution.class ]; then
    echo "You need to build OpenAMASE first, using \`./anod-build amase\`"
    return 2
fi

# Now, let's let the user know where we're working.
echo "Using run-example in ${UXAS_SOURCE_DIR}."
echo " "

# Pass arguments on to run-example
${UXAS_SOURCE_DIR}/run-example $@